project_id = "xhruetneyvdpryihwolq"

[functions.update-streak]
verify_jwt = true

[functions.fetch-economic-news]
verify_jwt = true

[functions.process-settlements]
verify_jwt = true

[functions.fetch-market-data]
verify_jwt = false
