import jsPDF from "jspdf";
import type { DeletionRequest } from "../hooks/useDataDeletion";

export const generateDeletionCertificate = (request: DeletionRequest, educatorName: string) => {
  const doc = new jsPDF({ format: "letter" });
  const margin = 25;
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const heading = (text: string, size: number) => {
    doc.setFontSize(size);
    doc.setFont("helvetica", "bold");
    doc.text(text, pageWidth / 2, y, { align: "center" });
    y += size * 0.5 + 4;
  };

  const body = (text: string) => {
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(text, contentWidth);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 4;
  };

  const field = (label: string, value: string) => {
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text(`${label}:`, margin, y);
    doc.setFont("helvetica", "normal");
    doc.text(value, margin + 60, y);
    y += 7;
  };

  // Header
  heading("DATA DELETION CERTIFICATE", 18);
  y += 2;
  heading("Compliance Verification Record", 12);

  // Border line
  doc.setDrawColor(100, 60, 200);
  doc.setLineWidth(1);
  doc.line(margin, y, pageWidth - margin, y);
  y += 12;

  body(
    "This certificate confirms that a data deletion request has been processed in accordance with the Family Educational Rights and Privacy Act (FERPA), the Children's Online Privacy Protection Act (COPPA), and applicable state data privacy laws."
  );
  y += 6;

  // Details
  heading("DELETION DETAILS", 13);
  y += 2;

  field("Certificate ID", request.id.toUpperCase());
  field("Student Name", request.student_name);
  field("Student ID", request.student_id);
  field("Class", request.class_name || "N/A");
  field("Deletion Type", request.deletion_type.charAt(0).toUpperCase() + request.deletion_type.slice(1));
  field("Requested By", educatorName);
  field("Requested At", new Date(request.requested_at).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }));
  field("Status", request.status.toUpperCase());

  if (request.purged_at) {
    field("Purged At", new Date(request.purged_at).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }));
  } else {
    field("Scheduled Purge", new Date(request.scheduled_purge_at).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }));
  }

  y += 6;

  // Data categories
  heading("DATA CATEGORIES INCLUDED", 13);
  y += 2;

  const categories = Array.isArray(request.data_categories) ? request.data_categories : [];
  const categoryLabels: Record<string, string> = {
    lesson_progress: "Lesson Progress & Completion Records",
    quiz_scores: "Quiz Scores & Assessment Data",
    game_sessions: "Game Session Records",
    achievements: "Achievement & Badge Records",
    messages: "Direct Messages & Communications",
    portfolio: "Portfolio & Trading Simulation Data",
    community_posts: "Community Posts, Comments & Likes",
  };

  categories.forEach((cat) => {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`• ${categoryLabels[cat] || cat}`, margin + 5, y);
    y += 6;
  });

  y += 8;

  // Certification statement
  doc.setDrawColor(100, 60, 200);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  body(
    "I certify that the above-referenced student data has been scheduled for permanent deletion from all Euphoria platform systems, including primary databases, cached copies, and analytical stores. This deletion is irreversible once the grace period has elapsed."
  );

  y += 10;

  // Signature lines
  doc.setDrawColor(150);
  doc.setLineWidth(0.3);
  doc.line(margin, y + 15, margin + 80, y + 15);
  doc.line(pageWidth - margin - 80, y + 15, pageWidth - margin, y + 15);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("Authorized By", margin, y + 20);
  doc.text("Date", pageWidth - margin - 80, y + 20);

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 15;
  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text(
    `Generated by Euphoria Platform on ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })} • Certificate ID: ${request.id}`,
    pageWidth / 2,
    footerY,
    { align: "center" }
  );

  doc.save(`deletion-certificate-${request.id.slice(0, 8)}.pdf`);
};
