-- Add more lessons to the lessons table
INSERT INTO public.lessons (title, description, content, difficulty, duration_minutes, order_index, is_locked) VALUES
('Options Trading Fundamentals', 'Learn the basics of call and put options, how they work, and when to use them.', 'Options are derivative contracts that give buyers the right, but not the obligation, to buy or sell an underlying asset at a specified price before a certain date. This lesson covers calls, puts, strike prices, expiration dates, and basic options strategies.', 'intermediate', 25, 15, false),
('ETFs and Index Funds', 'Understand the differences between ETFs and index funds and how to use them for diversification.', 'Exchange-traded funds (ETFs) and index funds are popular investment vehicles that track market indices. Learn about expense ratios, tracking error, and how to build a diversified portfolio using these instruments.', 'beginner', 15, 16, false),
('Bonds and Fixed Income', 'Explore the world of bonds, yields, and fixed-income investing strategies.', 'Bonds are debt securities issued by governments and corporations. This lesson covers bond pricing, yield calculations, duration, credit ratings, and the role of fixed income in a balanced portfolio.', 'intermediate', 20, 17, false),
('Market Cycles and Timing', 'Learn about bull and bear markets, economic cycles, and market timing strategies.', 'Understanding market cycles helps investors make better decisions. This lesson explores economic indicators, sector rotation, and the psychology behind market movements.', 'advanced', 30, 18, false),
('Cryptocurrency Basics', 'An introduction to Bitcoin, Ethereum, and the world of digital assets.', 'Cryptocurrency is a digital form of currency using cryptographic technology. Learn about blockchain, wallets, exchanges, and the risks and opportunities in crypto investing.', 'intermediate', 20, 19, false),
('Dividend Investing', 'Build passive income through dividend-paying stocks and dividend growth strategies.', 'Dividend investing focuses on companies that pay regular dividends. Learn about dividend yield, payout ratios, dividend aristocrats, and how to build a dividend income portfolio.', 'beginner', 15, 20, false),
('Technical Indicators Deep Dive', 'Master RSI, MACD, Bollinger Bands, and other essential technical indicators.', 'Technical indicators help traders identify trends and potential entry/exit points. This advanced lesson covers momentum indicators, volume analysis, and combining multiple indicators.', 'advanced', 35, 21, false),
('Real Estate Investment Trusts', 'Learn how REITs work and how to invest in real estate through the stock market.', 'REITs allow investors to own shares of real estate portfolios. Understand the different types of REITs, how they generate income, and their tax advantages.', 'intermediate', 20, 22, false),
('Margin Trading and Leverage', 'Understand the risks and mechanics of trading on margin and using leverage.', 'Margin trading allows investors to borrow money to increase their buying power. This lesson covers margin requirements, margin calls, and risk management strategies.', 'advanced', 25, 23, false),
('Building Your First Portfolio', 'A practical guide to constructing and maintaining your investment portfolio.', 'Apply everything you have learned to build your first investment portfolio. This lesson provides step-by-step guidance on asset selection, allocation, and ongoing portfolio management.', 'beginner', 20, 24, false);