-- Add lessons 13, 14, and 25-50 to reach 50 total lessons
INSERT INTO public.lessons (title, description, content, difficulty, duration_minutes, order_index, is_locked) VALUES
-- Missing lessons 13-14
('Technical Analysis Fundamentals', 'Learn to read price charts, identify trends, and use common technical patterns.', 'Technical analysis studies past price movements to predict future market behavior. This lesson covers chart types, trend lines, support/resistance levels, and volume analysis as tools for investment decisions.', 'intermediate', 20, 13, false),
('Investment Psychology', 'Master your emotions and avoid common psychological biases that hurt investors.', 'Psychology plays a crucial role in investment success. Learn about confirmation bias, loss aversion, herd mentality, and strategies to make rational decisions under pressure.', 'intermediate', 20, 14, false),

-- Lessons 25-50
('Short Selling Basics', 'Understand how to profit from declining stock prices and the risks involved.', 'Short selling involves borrowing shares to sell at current prices, hoping to buy back at lower prices. Learn the mechanics, risks including unlimited loss potential, and when short selling makes sense.', 'advanced', 25, 25, false),
('Sector Analysis', 'Learn to analyze and invest in different market sectors like technology, healthcare, and energy.', 'Different sectors perform differently across economic cycles. Understand sector rotation, cyclical vs defensive sectors, and how to identify promising sectors for investment.', 'intermediate', 20, 26, false),
('International Investing', 'Diversify globally with foreign stocks, ADRs, and international ETFs.', 'International investing provides exposure to global growth opportunities. Learn about currency risk, emerging vs developed markets, ADRs, and building a globally diversified portfolio.', 'intermediate', 25, 27, false),
('Retirement Account Strategies', 'Maximize your 401k, IRA, and Roth IRA for tax-advantaged growth.', 'Tax-advantaged accounts accelerate wealth building. Understand contribution limits, employer matching, Roth vs Traditional accounts, and optimal withdrawal strategies.', 'beginner', 20, 28, false),
('Estate Planning Basics', 'Protect and transfer your wealth to future generations effectively.', 'Estate planning ensures your assets pass to heirs efficiently. Learn about wills, trusts, beneficiary designations, and strategies to minimize estate taxes.', 'intermediate', 20, 29, false),
('Reading Annual Reports', 'Decode 10-K filings and annual reports to evaluate company health.', 'Annual reports contain crucial information for investors. Learn to read income statements, balance sheets, cash flow statements, and management discussion sections.', 'intermediate', 25, 30, false),
('Valuation Methods Deep Dive', 'Master DCF, comparable analysis, and other professional valuation techniques.', 'Professional investors use multiple valuation methods. Understand discounted cash flow analysis, P/E comparables, EV/EBITDA, and when to use each method.', 'advanced', 30, 31, false),
('Earnings Season Strategies', 'Navigate quarterly earnings reports and capitalize on market reactions.', 'Earnings season creates volatility and opportunity. Learn to interpret earnings beats/misses, guidance updates, and position portfolios around earnings announcements.', 'intermediate', 20, 32, false),
('IPO Investing', 'Evaluate and invest in initial public offerings wisely.', 'IPOs can offer exciting opportunities but carry unique risks. Learn about the IPO process, lockup periods, valuation concerns, and when to participate.', 'intermediate', 20, 33, false),
('Small Cap Investing', 'Find hidden gems in smaller companies with growth potential.', 'Small cap stocks offer higher growth potential with increased volatility. Learn research techniques, risk management, and how to identify promising small companies.', 'advanced', 25, 34, false),
('Growth vs Value Investing', 'Compare two fundamental investment philosophies and find your style.', 'Growth investors seek rapidly expanding companies; value investors seek underpriced opportunities. Understand both philosophies, their historical performance, and when each works best.', 'intermediate', 20, 35, false),
('Momentum Trading Strategies', 'Use price momentum to identify trending stocks and optimal entry points.', 'Momentum investing buys rising stocks and sells falling ones. Learn momentum indicators, trend-following strategies, and when momentum strategies outperform.', 'advanced', 25, 36, false),
('Contrarian Investing', 'Profit by going against the crowd when markets overreact.', 'Contrarian investors buy when others panic and sell when others are greedy. Learn to identify market extremes, value opportunities in fear, and manage contrarian risk.', 'advanced', 25, 37, false),
('Hedging Your Portfolio', 'Protect your investments using options and other hedging strategies.', 'Hedging reduces portfolio risk during uncertain times. Learn about protective puts, collars, inverse ETFs, and when hedging makes sense for your portfolio.', 'advanced', 30, 38, false),
('Alternative Investments', 'Explore commodities, hedge funds, and other alternative assets.', 'Alternative investments provide diversification beyond stocks and bonds. Understand commodities, private equity, hedge funds, and their role in portfolio construction.', 'advanced', 25, 39, false),
('ESG and Sustainable Investing', 'Invest according to environmental, social, and governance principles.', 'ESG investing aligns portfolios with personal values. Learn about ESG ratings, sustainable funds, impact investing, and whether ESG affects returns.', 'beginner', 20, 40, false),
('Factor Investing', 'Use academic factors like value, momentum, and size to enhance returns.', 'Factor investing applies research-backed strategies. Understand the value, size, momentum, quality, and low volatility factors and how to implement them.', 'advanced', 30, 41, false),
('Algorithmic Trading Concepts', 'Understand how algorithms and quantitative strategies work in markets.', 'Algorithmic trading uses computer programs to execute strategies. Learn about quant strategies, high-frequency trading, and how algorithms impact markets.', 'advanced', 25, 42, false),
('Tax Loss Harvesting', 'Reduce your tax bill by strategically realizing investment losses.', 'Tax loss harvesting offsets gains with losses to reduce taxes. Learn the wash sale rule, optimal harvesting strategies, and how to implement tax-efficient investing.', 'intermediate', 20, 43, false),
('Inflation Protection Strategies', 'Shield your portfolio from inflation using TIPS, commodities, and real assets.', 'Inflation erodes purchasing power. Learn about Treasury Inflation-Protected Securities, commodities, real estate, and other inflation hedges.', 'intermediate', 20, 44, false),
('Market Orders and Execution', 'Master order types and get the best execution for your trades.', 'Different order types serve different purposes. Understand market orders, limit orders, stop orders, and how to avoid common execution mistakes.', 'beginner', 15, 45, false),
('Building a Watchlist', 'Create and manage an effective stock watchlist for opportunities.', 'A good watchlist helps identify buying opportunities. Learn screening criteria, alert systems, and how to organize stocks you are monitoring.', 'beginner', 15, 46, false),
('Investment Mistakes to Avoid', 'Learn from common investor errors and protect your capital.', 'Even experienced investors make mistakes. Understand common pitfalls like overtrading, chasing performance, ignoring fees, and how to avoid them.', 'beginner', 20, 47, false),
('Building Passive Income', 'Create investment income streams through dividends, bonds, and REITs.', 'Passive income from investments can fund your lifestyle. Learn to build a portfolio generating reliable income through dividends, interest, and distributions.', 'intermediate', 20, 48, false),
('Financial Independence Planning', 'Calculate your FI number and create a roadmap to financial freedom.', 'Financial independence means your investments cover living expenses. Learn to calculate your FI number, safe withdrawal rates, and the path to financial freedom.', 'intermediate', 25, 49, false),
('Becoming a Complete Investor', 'Integrate all your learning into a comprehensive investment strategy.', 'This final lesson ties everything together. Create your personal investment policy statement, review your strategy annually, and continue your education journey.', 'intermediate', 30, 50, false);