-- Clear existing lesson progress and lessons to rebuild curriculum
DELETE FROM lesson_question_performance;
DELETE FROM ai_lesson_interactions;
DELETE FROM user_lesson_progress;
DELETE FROM lessons;

-- ============================================
-- INVESTING FUNDAMENTALS (25 lessons)
-- ============================================
INSERT INTO lessons (title, description, content, difficulty, duration_minutes, order_index, pathway, is_locked) VALUES
('What is Investing?', 'Learn the difference between saving and investing, and why your money needs to grow.', 'investing-basics', 'beginner', 8, 1, 'investing', false),
('Risk vs. Reward', 'Understand the fundamental tradeoff at the heart of every investment decision.', 'risk-reward', 'beginner', 8, 2, 'investing', true),
('The Power of Compound Interest', 'See how small amounts grow exponentially over time through compounding.', 'compound-interest', 'beginner', 10, 3, 'investing', true),
('Stocks vs. Bonds', 'Compare the two foundational asset classes and when to use each.', 'stocks-bonds', 'beginner', 10, 4, 'investing', true),
('What is Diversification?', 'Learn why spreading your investments reduces risk without sacrificing returns.', 'diversification', 'beginner', 10, 5, 'investing', true),
('Understanding Market Indexes', 'Discover what the S&P 500, Dow, and NASDAQ actually track and why they matter.', 'market-indexes', 'beginner', 8, 6, 'investing', true),
('ETFs and Mutual Funds', 'Learn how funds let you invest in hundreds of companies with a single purchase.', 'etfs-mutual-funds', 'beginner', 10, 7, 'investing', true),
('How to Read a Stock Quote', 'Decode ticker symbols, price, volume, market cap, P/E ratio, and more.', 'reading-stock-quotes', 'beginner', 8, 8, 'investing', true),
('Dollar-Cost Averaging', 'Master the strategy of investing fixed amounts at regular intervals to reduce timing risk.', 'dca-strategy', 'beginner', 10, 9, 'investing', true),
('Your First Portfolio', 'Build a balanced starter portfolio using the concepts from lessons 1-9.', 'first-portfolio', 'beginner', 15, 10, 'investing', true),
('Value Investing Basics', 'Learn Warren Buffett''s approach: finding great companies at fair prices.', 'value-investing', 'intermediate', 12, 11, 'investing', true),
('Growth vs. Value Stocks', 'Compare two dominant investing styles and understand when each outperforms.', 'growth-vs-value', 'intermediate', 10, 12, 'investing', true),
('Understanding Dividends', 'Learn how companies share profits and how to build a dividend income stream.', 'dividends', 'intermediate', 10, 13, 'investing', true),
('Market Psychology & Emotions', 'Recognize fear, greed, and herd mentality — and how they create opportunity.', 'market-psychology', 'intermediate', 12, 14, 'investing', true),
('Bull and Bear Markets', 'Understand market cycles and strategies for thriving in both up and down markets.', 'bull-bear-markets', 'intermediate', 10, 15, 'investing', true),
('Introduction to Technical Analysis', 'Learn to read price charts, trends, support, and resistance levels.', 'technical-analysis-intro', 'intermediate', 12, 16, 'investing', true),
('Understanding P/E Ratios', 'Master the most widely used valuation metric and its limitations.', 'pe-ratios', 'intermediate', 10, 17, 'investing', true),
('Sector Analysis', 'Learn to analyze different market sectors and rotate between them strategically.', 'sector-analysis', 'intermediate', 12, 18, 'investing', true),
('REITs: Investing in Real Estate', 'Access real estate returns through the stock market without buying property.', 'reits', 'intermediate', 10, 19, 'investing', true),
('International Investing', 'Diversify globally with foreign stocks, ADRs, and international ETFs.', 'international-investing', 'intermediate', 15, 20, 'investing', true),
('Margin and Leverage', 'Understand borrowed money in investing — the amplified gains and amplified risks.', 'margin-leverage', 'advanced', 12, 21, 'investing', true),
('Options Basics', 'Learn calls, puts, and how options contracts work at a foundational level.', 'options-basics', 'advanced', 15, 22, 'investing', true),
('Short Selling Explained', 'Understand how investors profit from falling prices and the risks involved.', 'short-selling', 'advanced', 12, 23, 'investing', true),
('Building a Long-Term Strategy', 'Create a personalized investment plan aligned with your goals and timeline.', 'long-term-strategy', 'advanced', 12, 24, 'investing', true),
('Investing Capstone Project', 'Apply everything you''ve learned in a comprehensive portfolio-building challenge.', 'investing-capstone', 'advanced', 15, 25, 'investing', true),

-- ============================================
-- PERSONAL FINANCE (25 lessons)
-- ============================================
('Why Personal Finance Matters', 'Understand how managing money impacts every area of your life.', 'pf-intro', 'beginner', 8, 1, 'personal_finance', false),
('Income and Expenses', 'Track where your money comes from and where it goes each month.', 'income-expenses', 'beginner', 8, 2, 'personal_finance', true),
('Creating a Budget', 'Build a practical budget using the 50/30/20 rule and other methods.', 'budgeting', 'beginner', 10, 3, 'personal_finance', true),
('Emergency Funds', 'Learn why you need 3-6 months of expenses saved and how to build it.', 'emergency-fund', 'beginner', 8, 4, 'personal_finance', true),
('Understanding Credit Scores', 'Decode the 300-850 scale and learn what builds or destroys your score.', 'credit-scores', 'beginner', 10, 5, 'personal_finance', true),
('Debt: Good vs. Bad', 'Distinguish between leverage that builds wealth and debt that destroys it.', 'good-bad-debt', 'beginner', 8, 6, 'personal_finance', true),
('Paying Off Debt Strategically', 'Compare avalanche vs. snowball methods and find the right approach for you.', 'debt-payoff', 'beginner', 10, 7, 'personal_finance', true),
('Banking Basics', 'Choose between checking, savings, CDs, and high-yield accounts wisely.', 'banking-basics', 'beginner', 8, 8, 'personal_finance', true),
('Understanding Interest Rates', 'Learn how APR, APY, and the Federal Reserve rate affect your money daily.', 'interest-rates', 'beginner', 10, 9, 'personal_finance', true),
('Smart Spending Habits', 'Build a starter financial plan combining budgeting, saving, and debt management.', 'smart-spending', 'beginner', 15, 10, 'personal_finance', true),
('Introduction to Taxes', 'Understand tax brackets, deductions, credits, and how to keep more of your money.', 'taxes-intro', 'intermediate', 12, 11, 'personal_finance', true),
('Retirement Accounts (401k & IRA)', 'Compare Roth vs Traditional accounts and employer matching strategies.', 'retirement-accounts', 'intermediate', 12, 12, 'personal_finance', true),
('Health Insurance Decoded', 'Navigate premiums, deductibles, copays, HSAs, and choosing the right plan.', 'health-insurance', 'intermediate', 10, 13, 'personal_finance', true),
('Renting vs. Buying a Home', 'Analyze the true cost of homeownership versus renting in different scenarios.', 'rent-vs-buy', 'intermediate', 12, 14, 'personal_finance', true),
('Understanding Mortgages', 'Learn fixed vs. adjustable rates, down payments, and amortization schedules.', 'mortgages', 'intermediate', 12, 15, 'personal_finance', true),
('Car Buying: Financing & Leasing', 'Make smart vehicle decisions by comparing buying, financing, and leasing.', 'car-buying', 'intermediate', 10, 16, 'personal_finance', true),
('College Savings & Student Loans', 'Navigate 529 plans, scholarships, and student loan repayment strategies.', 'college-savings', 'intermediate', 12, 17, 'personal_finance', true),
('Insurance Beyond Health', 'Understand life, auto, renters, and disability insurance essentials.', 'insurance-types', 'intermediate', 10, 18, 'personal_finance', true),
('Negotiating Your Salary', 'Learn research-backed negotiation techniques to maximize your earning potential.', 'salary-negotiation', 'intermediate', 10, 19, 'personal_finance', true),
('Side Income & Freelancing', 'Explore ways to diversify your income streams beyond your primary job.', 'side-income', 'intermediate', 15, 20, 'personal_finance', true),
('Estate Planning Basics', 'Understand wills, trusts, beneficiaries, and protecting your assets.', 'estate-planning', 'advanced', 12, 21, 'personal_finance', true),
('Tax-Advantaged Investing', 'Maximize returns by using tax-loss harvesting, HSAs, and strategic account placement.', 'tax-optimization', 'advanced', 12, 22, 'personal_finance', true),
('Inflation and Your Purchasing Power', 'Learn how inflation erodes wealth and strategies to stay ahead of it.', 'inflation-purchasing-power', 'advanced', 10, 23, 'personal_finance', true),
('Financial Independence (FIRE)', 'Calculate your FIRE number and build a path to optional early retirement.', 'fire-movement', 'advanced', 12, 24, 'personal_finance', true),
('Personal Finance Capstone', 'Create a comprehensive life financial plan from budget to retirement.', 'pf-capstone', 'advanced', 15, 25, 'personal_finance', true),

-- ============================================
-- CORPORATE FINANCE (25 lessons)
-- ============================================
('What is Corporate Finance?', 'Understand how companies make financial decisions to maximize shareholder value.', 'corp-finance-intro', 'beginner', 8, 1, 'corporate_finance', false),
('Reading Income Statements', 'Decode revenue, COGS, operating income, and net profit from real company filings.', 'income-statements', 'beginner', 10, 2, 'corporate_finance', true),
('Understanding Balance Sheets', 'Learn assets, liabilities, and equity — the snapshot of a company''s health.', 'balance-sheets', 'beginner', 10, 3, 'corporate_finance', true),
('Cash Flow Statements', 'Analyze operating, investing, and financing cash flows to assess true profitability.', 'cash-flow-statements', 'beginner', 10, 4, 'corporate_finance', true),
('Key Financial Ratios', 'Master P/E, ROE, debt-to-equity, current ratio, and quick ratio analysis.', 'financial-ratios', 'beginner', 10, 5, 'corporate_finance', true),
('Revenue Recognition', 'Understand when and how companies record revenue and why it matters to investors.', 'revenue-recognition', 'beginner', 8, 6, 'corporate_finance', true),
('Profit Margins Explained', 'Compare gross, operating, and net margins to evaluate business efficiency.', 'profit-margins', 'beginner', 8, 7, 'corporate_finance', true),
('Introduction to Valuation', 'Learn the core principles of determining what a company is truly worth.', 'valuation-intro', 'beginner', 10, 8, 'corporate_finance', true),
('Earnings Per Share (EPS)', 'Understand basic and diluted EPS and what they reveal about profitability.', 'eps', 'beginner', 8, 9, 'corporate_finance', true),
('Financial Statements Challenge', 'Analyze a real company''s financials in a timed comprehensive assessment.', 'financials-challenge', 'beginner', 15, 10, 'corporate_finance', true),
('DCF Valuation Method', 'Master discounted cash flow analysis — the gold standard of company valuation.', 'dcf-valuation', 'intermediate', 15, 11, 'corporate_finance', true),
('Comparable Company Analysis', 'Learn to value companies by comparing them to similar publicly traded peers.', 'comparable-analysis', 'intermediate', 12, 12, 'corporate_finance', true),
('Capital Structure', 'Explore how companies balance debt and equity to optimize their cost of capital.', 'capital-structure', 'intermediate', 12, 13, 'corporate_finance', true),
('Cost of Capital (WACC)', 'Calculate weighted average cost of capital and understand its role in decisions.', 'wacc', 'intermediate', 15, 14, 'corporate_finance', true),
('Capital Budgeting', 'Evaluate projects using NPV, IRR, and payback period analysis.', 'capital-budgeting', 'intermediate', 12, 15, 'corporate_finance', true),
('Working Capital Management', 'Optimize inventory, receivables, and payables for operational efficiency.', 'working-capital', 'intermediate', 10, 16, 'corporate_finance', true),
('Dividend Policy', 'Understand how companies decide between dividends, buybacks, and reinvestment.', 'dividend-policy', 'intermediate', 10, 17, 'corporate_finance', true),
('Reading 10-K Filings', 'Navigate SEC filings like a professional analyst to find hidden insights.', 'reading-10k', 'intermediate', 12, 18, 'corporate_finance', true),
('Corporate Governance', 'Evaluate board structures, executive compensation, and shareholder rights.', 'corporate-governance', 'intermediate', 10, 19, 'corporate_finance', true),
('Industry Analysis', 'Use Porter''s Five Forces and competitive analysis to evaluate business moats.', 'industry-analysis', 'intermediate', 15, 20, 'corporate_finance', true),
('Mergers & Acquisitions', 'Analyze M&A deals, synergies, and their impact on shareholder value.', 'mergers-acquisitions', 'advanced', 15, 21, 'corporate_finance', true),
('IPO Analysis', 'Evaluate initial public offerings, pricing, and post-IPO performance patterns.', 'ipo-analysis', 'advanced', 12, 22, 'corporate_finance', true),
('Corporate Restructuring', 'Understand spin-offs, divestitures, and turnaround strategies.', 'restructuring', 'advanced', 12, 23, 'corporate_finance', true),
('Forensic Accounting', 'Detect earnings manipulation, creative accounting, and financial red flags.', 'forensic-accounting', 'advanced', 12, 24, 'corporate_finance', true),
('Corporate Finance Capstone', 'Complete a full company analysis — from financials to valuation to recommendation.', 'corp-finance-capstone', 'advanced', 15, 25, 'corporate_finance', true),

-- ============================================
-- TRADING & TECHNICAL ANALYSIS (25 lessons)
-- ============================================
('What is Trading?', 'Understand the difference between trading and investing, and different trading styles.', 'trading-intro', 'beginner', 8, 1, 'trading', false),
('How Markets Work', 'Learn about exchanges, market makers, bid-ask spreads, and order execution.', 'how-markets-work', 'beginner', 10, 2, 'trading', true),
('Order Types Explained', 'Master market, limit, stop-loss, and stop-limit orders for precise execution.', 'order-types', 'beginner', 10, 3, 'trading', true),
('Reading Candlestick Charts', 'Decode the most popular chart type: open, high, low, close, and patterns.', 'candlestick-charts', 'beginner', 10, 4, 'trading', true),
('Support and Resistance', 'Identify key price levels where buying and selling pressure concentrate.', 'support-resistance', 'beginner', 10, 5, 'trading', true),
('Trend Lines and Channels', 'Draw and use trend lines to identify market direction and trading ranges.', 'trend-lines', 'beginner', 8, 6, 'trading', true),
('Volume Analysis', 'Understand how trading volume confirms or contradicts price movements.', 'volume-analysis', 'beginner', 8, 7, 'trading', true),
('Moving Averages', 'Learn SMA, EMA, and how moving averages signal trend changes and entries.', 'moving-averages', 'beginner', 10, 8, 'trading', true),
('Chart Patterns: Part 1', 'Identify head & shoulders, double tops/bottoms, and triangles on charts.', 'chart-patterns-1', 'beginner', 12, 9, 'trading', true),
('Technical Analysis Challenge', 'Apply your charting skills in a real-time pattern recognition assessment.', 'ta-challenge', 'beginner', 15, 10, 'trading', true),
('RSI and Momentum Indicators', 'Use Relative Strength Index to identify overbought and oversold conditions.', 'rsi-momentum', 'intermediate', 12, 11, 'trading', true),
('MACD: Trend and Momentum', 'Master the Moving Average Convergence Divergence indicator for trade signals.', 'macd', 'intermediate', 10, 12, 'trading', true),
('Bollinger Bands', 'Use volatility bands to identify breakouts, squeezes, and mean reversion.', 'bollinger-bands', 'intermediate', 10, 13, 'trading', true),
('Fibonacci Retracements', 'Apply Fibonacci levels to predict pullback targets and reversal zones.', 'fibonacci', 'intermediate', 12, 14, 'trading', true),
('Chart Patterns: Part 2', 'Master flags, pennants, wedges, and cup-and-handle patterns.', 'chart-patterns-2', 'intermediate', 12, 15, 'trading', true),
('Risk Management for Traders', 'Learn position sizing, stop-losses, and the 1% rule to protect your capital.', 'risk-management-trading', 'intermediate', 12, 16, 'trading', true),
('Trading Psychology', 'Overcome fear, greed, revenge trading, and build emotional discipline.', 'trading-psychology', 'intermediate', 10, 17, 'trading', true),
('Backtesting Strategies', 'Learn to test trading strategies against historical data before risking capital.', 'backtesting', 'intermediate', 12, 18, 'trading', true),
('Day Trading vs. Swing Trading', 'Compare timeframes, strategies, and lifestyle differences between styles.', 'day-vs-swing', 'intermediate', 10, 19, 'trading', true),
('Building a Trading Plan', 'Create a systematic rules-based trading plan with entry, exit, and risk rules.', 'trading-plan', 'intermediate', 15, 20, 'trading', true),
('Advanced Candlestick Patterns', 'Master engulfing, doji, hammer, and other high-probability reversal signals.', 'advanced-candlesticks', 'advanced', 12, 21, 'trading', true),
('Multi-Timeframe Analysis', 'Combine daily, weekly, and intraday charts for higher-probability trades.', 'multi-timeframe', 'advanced', 12, 22, 'trading', true),
('Algorithmic Trading Basics', 'Understand automated strategies, quantitative signals, and algo trading concepts.', 'algo-trading', 'advanced', 15, 23, 'trading', true),
('Market Microstructure', 'Learn about dark pools, HFT, order flow, and how modern markets really work.', 'market-microstructure', 'advanced', 12, 24, 'trading', true),
('Trading Capstone Project', 'Develop and backtest a complete trading strategy from idea to execution plan.', 'trading-capstone', 'advanced', 15, 25, 'trading', true),

-- ============================================
-- ALTERNATIVE ASSETS (25 lessons)
-- ============================================
('Beyond Stocks and Bonds', 'Discover asset classes outside traditional markets and why they matter.', 'alt-intro', 'beginner', 8, 1, 'alternatives', false),
('Real Estate Investing 101', 'Learn the fundamentals of real estate as an investment asset class.', 'real-estate-101', 'beginner', 10, 2, 'alternatives', true),
('REITs: Real Estate on the Stock Market', 'Invest in real estate through publicly traded REITs without buying property.', 'reits-intro', 'beginner', 10, 3, 'alternatives', true),
('Cryptocurrency Fundamentals', 'Understand Bitcoin, Ethereum, blockchain technology, and digital assets.', 'crypto-fundamentals', 'beginner', 10, 4, 'alternatives', true),
('Gold and Precious Metals', 'Learn why gold has been a store of value for millennia and how to invest in it.', 'gold-precious-metals', 'beginner', 8, 5, 'alternatives', true),
('Commodities: Oil, Gas, and Agriculture', 'Understand how commodity markets work and their role in a portfolio.', 'commodities', 'beginner', 10, 6, 'alternatives', true),
('What Are Hedge Funds?', 'Demystify hedge funds: their strategies, fees, and role in the financial ecosystem.', 'hedge-funds-intro', 'beginner', 8, 7, 'alternatives', true),
('Private Equity Basics', 'Learn how PE firms acquire, improve, and sell companies for profit.', 'private-equity', 'beginner', 10, 8, 'alternatives', true),
('Venture Capital 101', 'Understand how VCs fund startups and the risk/reward profile of early-stage investing.', 'venture-capital', 'beginner', 10, 9, 'alternatives', true),
('Alternative Assets Challenge', 'Test your understanding of non-traditional investments in a scenario challenge.', 'alt-challenge', 'beginner', 15, 10, 'alternatives', true),
('DeFi: Decentralized Finance', 'Explore lending, staking, yield farming, and the DeFi ecosystem.', 'defi', 'intermediate', 12, 11, 'alternatives', true),
('NFTs and Digital Collectibles', 'Understand NFTs beyond the hype — technology, use cases, and investment risks.', 'nfts', 'intermediate', 10, 12, 'alternatives', true),
('ESG and Impact Investing', 'Invest according to environmental, social, and governance principles.', 'esg-investing', 'intermediate', 10, 13, 'alternatives', true),
('International and Emerging Markets', 'Diversify globally with foreign stocks, ADRs, and developing economy exposure.', 'emerging-markets', 'intermediate', 12, 14, 'alternatives', true),
('Collectibles: Art, Wine, and More', 'Explore alternative tangible assets as potential investments.', 'collectibles', 'intermediate', 10, 15, 'alternatives', true),
('Factor Investing', 'Use academic factors like value, momentum, size, and quality to enhance returns.', 'factor-investing', 'intermediate', 12, 16, 'alternatives', true),
('Infrastructure Investing', 'Learn about investments in roads, bridges, utilities, and public works.', 'infrastructure', 'intermediate', 10, 17, 'alternatives', true),
('Farmland and Timber', 'Explore agricultural land and timber as inflation-hedging asset classes.', 'farmland-timber', 'intermediate', 10, 18, 'alternatives', true),
('Crowdfunding and Angel Investing', 'Access startup and real estate investing through crowdfunding platforms.', 'crowdfunding', 'intermediate', 10, 19, 'alternatives', true),
('Building an Alternatives Portfolio', 'Learn optimal allocation strategies for incorporating alternatives.', 'alt-portfolio', 'intermediate', 15, 20, 'alternatives', true),
('Crypto Trading Strategies', 'Learn DCA, swing trading, and portfolio management for digital assets.', 'crypto-strategies', 'advanced', 12, 21, 'alternatives', true),
('Hedge Fund Strategies Deep Dive', 'Explore long/short equity, global macro, event-driven, and quant strategies.', 'hedge-fund-strategies', 'advanced', 15, 22, 'alternatives', true),
('Private Market Investing', 'Navigate private placements, secondary markets, and illiquidity premiums.', 'private-markets', 'advanced', 12, 23, 'alternatives', true),
('Risk Management for Alternatives', 'Manage liquidity risk, correlation, and due diligence for non-traditional assets.', 'alt-risk-management', 'advanced', 12, 24, 'alternatives', true),
('Alternatives Capstone Project', 'Build a diversified portfolio incorporating traditional and alternative assets.', 'alt-capstone', 'advanced', 15, 25, 'alternatives', true);